const quotes = [
  "Discipline is doing what needs to be done, even when you don’t feel like doing it.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "Success is the sum of small efforts repeated day in and day out.",
  "Push yourself, because no one else is going to do it for you.",
  "Don’t watch the clock; do what it does. Keep going.",
  "Work hard in silence, let your success be your noise.",
  "Doubt kills more dreams than failure ever will.",
  "If you’re going through hell, keep going.",
  "Small steps every day add up to big results.",
  "Great things never come from comfort zones.",
  "It always seems impossible until it's done.",
  "Winners are not afraid of losing. But losers are.",
  "Be stronger than your strongest excuse.",
  "Dream it. Believe it. Build it.",
  "Your only limit is you.",
  "Stay hungry, stay foolish.",
  "The grind never lies.",
  "Make it happen. Shock everyone.",
  "Discipline is the bridge between goals and accomplishment.",
  "The best view comes after the hardest climb.",
  "Hard work beats talent when talent doesn’t work hard.",
  "Success doesn’t come from what you do occasionally. It comes from what you do consistently.",
  "Wake up with determination. Go to bed with satisfaction.",
  "You don’t have to be extreme, just consistent.",
  "The man who moves a mountain begins by carrying small stones.",
  "Success is no accident. It is hard work, perseverance, and love for what you do.",
  "Fall seven times, stand up eight.",
  "One day or day one. You decide.",
  "Stay focused. Stay humble. Stay strong.",
  "Your future is created by what you do today, not tomorrow.",
  "Grind in silence. Let your hustle make the noise.",
  "Motivation gets you going, but discipline keeps you growing.",
  "Excuses don’t get results.",
  "Action is the foundational key to all success.",
  "Nobody cares. Work harder.",
  "Success is not for the lazy.",
  "The difference between ordinary and extraordinary is that little extra.",
  "Be fearless in the pursuit of what sets your soul on fire.",
  "You are your only competition.",
  "Don’t limit your challenges. Challenge your limits.",
  "A river cuts through rock not because of its power, but because of its persistence.",
  "Discipline turns dreams into reality.",
  "Pain is temporary. Quitting lasts forever.",
  "Every accomplishment starts with the decision to try.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "You miss 100% of the shots you don’t take.",
  "There is no elevator to success — you have to take the stairs.",
  "The secret of your future is hidden in your daily routine.",
  "Better sore than sorry.",
  "Train your mind to be stronger than your emotions.",
];

const today = new Date();
const dayOfYear = Math.floor(
  (today - new Date(today.getFullYear(), 0, 0)) / 86400000
);
const quote = quotes[dayOfYear % quotes.length];
document.getElementById("quote").innerText = quote;
